# A Heat environment file which can be used to enable a
# a Cinder Pure backend, configured via puppet
resource_registry:
  OS::TripleO::ControllerExtraConfigPre: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/controller/cinder-pure.yaml

parameter_defaults:
  CinderEnablePureBackend: true
  CinderPureBackendName: 'tripleo_pure'
  CinderPureSanIp: ''
  CinderPureAPIToken: ''
  CinderPureUseChap: false
  CinderPureMultipathXfer: true
