heat_template_version: 2015-10-15

description: Sets up MPIO and udev rules on all nodes

parameters:
  server:
    type: string

resources:
    PureSetup:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        cat <<EOF >>/tmp/multipath.conf
        defaults {
             polling_interval       5
        }
        devices {
          device {
               vendor                   "PURE"
               path_selector            "queue-length 0"
               path_grouping_policy     multibus
               path_checker             tur
               fast_io_fail_tmo         10
               dev_loss_tmo             60
               user_friendly_names      no
               no_path_retry            0
               features                 0
               }
        }
        EOF
        sudo cp /tmp/multipath.conf /etc/multipath.conf
        sudo service multipathd reload 
        cat <<EOF >>/tmp/99-pure-storage.rules
        ACTION=="add|change", KERNEL=="sd*[!0-9]", SUBSYSTEM=="block", ENV{ID_VENDOR}=="PURE", ATTR{queue/max_sectors_kb}="4096"
        # Use noop scheduler for high-performance solid-state storage
        ACTION=="add|change", KERNEL=="sd*[!0-9]", SUBSYSTEM=="block", ENV{ID_VENDOR}=="PURE", ATTR{queue/scheduler}="noop"
        # Reduce CPU overhead due to entropy collection
        ACTION=="add|change", KERNEL=="sd*[!0-9]", SUBSYSTEM=="block", ENV{ID_VENDOR}=="PURE", ATTR{queue/add_random}="0"
        # Spread CPU load by redirecting completions to originating CPU
        ACTION=="add|change", KERNEL=="sd*[!0-9]", SUBSYSTEM=="block", ENV{ID_VENDOR}=="PURE", ATTR{queue/rq_affinity}="2"
        # Set the HBA timeout to 60 seconds
        ACTION=="add", SUBSYSTEMS=="scsi", ATTRS{model}=="FlashArray      ", RUN+="/bin/sh -c 'echo 60 > /sys/$DEVPATH/device/timeout'"
        EOF
        sudo cp /tmp/99-pure-storage.rules /etc/udev/rules.d/99-pure-storage.rules
        sudo /sbin/udevadm control --reload-rules
        sudo /sbin/udevadm trigger --type=devices --action=change

    ExtraDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: PureSetup}
      server: {get_param: server}
      actions: [CREATE,UPDATE]
