# A Heat environment file which can be used to enable a
# Cinder Pure Storage FlashArray iSCSI backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendPure: /usr/share/openstack-tripleo-heat-templates/puppet/services/cinder-backend-pure.yaml
  OS::TripleO::NodeExtraConfigPost: /home/stack/templates/pure/pure-temp.yaml

parameter_defaults:
  CinderEnablePureBackend: true
  CinderPureBackendName: 'tripleo_pure'
  CinderPureStorageProtocol: 'iSCSI'  # or 'FC'
  CinderPureSanIp: ''
  CinderPureAPIToken: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  CinderPureUseChap: false
  CinderPureMultipathXfer: true
  CinderPureImageCache: true
