# A Heat environment file which can be used to enable a
# Manila Pure Storage FlashBlade backend, configured via puppet
resource_registry:
  OS::TripleO::Services::ManilaBackendFlashBlade: /usr/share/openstack-tripleo-heat-templates/deployment/manila/manila-backend-flashblade-puppet.yaml

parameter_defaults:
  ManilaFlashBladeBackendName: 'tripleo_flashblade'
  ManilaFlashBladeMgmtIp: ''
  ManilaFlashBladeDataIp: ''
  ManilaFlashBladeAPIToken: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  ManilaFlashBladeEradicate: true
