# A Heat environment file which can be used to enable a
# a Cinder Pure backend, configured via puppet
resource_registry:
  OS::TripleO::ControllerExtraConfigPre: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/controller/cinder-pure.yaml
  OS::TripleO::ControllerExtraConfig: /home/stack/templates/pure-controller-temp.yaml
  OS::TripleO::NodeExtraConfigPost: /home/stack/templates/pure-temp.yaml

parameter_defaults:
  CinderEnablePureBackend: true
  CinderPureBackendName: 'tripleo_pure'
  CinderPureSanIp: ''
  CinderPureAPIToken: ''
  CinderPureUseChap: false
  CinderPureStorageProtocol: 'iSCSI'  # or 'FC'
  CinderPureMultipathXfer: true
